name: PipelineAS1

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Python version
        run: python3 -V

  security-test:
    runs-on: ubuntu-latest
    needs: [build-job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run SAST with SonarQube
        run: |

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job, security-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: pull and run Docker image
        run: |
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{secrets.TAG}}
          docker run ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{secrets.TAG}}